name: midi
description: A midi binding to ALSA midi using FFI
version: 0.0.1
homepage: https://github.com/maks/midi
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  ffi: ^1.0.0
  tuple: ^2.0.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
