name: midi
description: A Dart binding to ALSA midi using FFI
version: 0.0.3
homepage: https://github.com/maks/dart_midi
environment:
  sdk: '>=2.12.0 <3.0.0'

# Supports only Linux
platforms:
  linux:

dependencies:
  ffi: ^1.0.0
  tuple: ^2.0.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
